### ISSUE TITLE
ADB install timeout

### ISSUE THREAD

**Issue by lukaville** [gojuno/composer#25]
I am using Spoon to run instrumentation tests and I am trying to migrate to Composer.

Sometimes Composer fails with `TimeoutException` (log: https://gist.github.com/lukaville/41d105ca9082b8168f58c034f56a6542). It always fails at 24% (I tried to change timeout in `installApk` extension function and it didn't help, it fails at 24% too).

After this exception I can't connect to emulator via adb (even from other machine). It says that "device offline", but emulator is running and I can use it through UI.

In README.md mentioned that adb install timeout problems occurs when using Spoon, but I have absolutely opposite result: with patched composer that uses ddmlib to install apks, timeout exceptions vanished.

Anyone have any guesses about cause of the problem? Thanks.

**Comment by artem-zinnatullin** [comment]
Well that's funny :)

I saw this only twice in our setup, ~1k builds with Composer now (each build uses 6 emulators on same machine) while Spoon was failing with very huge rate ~50%.

If you can't work with emulator from `adb` that may mean that something gone wrong pretty badly and not sure Composer can do anything about it.

>After this exception I can't connect to emulator via adb (even from other machine). It says that "device offline", but emulator is running and I can use it through UI.

As seen from your log, you're working with adb device over tcp/ip (which is fine) and since install always stops on 24% I suppose it's network related problem, probably problem is in adb-over-network communication.

Can you please file a bug on http://b.android.com and crosslink it with this issue (post it there in description and here as a comment)? Please attach as max info about your adb over network setup as possible.

Also, have you tried to restart adb server on machine that runs it and connect to emulator after that?

**Comment by artem-zinnatullin** [comment]
Ok, we've started seeing this as well… Investigating

**Comment by artem-zinnatullin** [comment]
We haven't seen this since May 20th in about 80 builds per day, I'm closing this for now, if you have more info feel free to add it to the issue.
