### ISSUE TITLE
Screenshots are not beeing pulled from device

### ISSUE THREAD

**Issue by RodrigoAmaroEng** [gojuno/composer#97]
I've tried with many different emulators and real devices but although the tests run perfectly, the screenshots are not beeing pulled from device. Is there any trick or recommendation about it?

**Comment by artem-zinnatullin** [comment]
Do you actually take them during the tests?

Composer doesn't do screenshots on its own, because it doesn't know when to do them and how to name them. It expects screenshots to appear in [folder structure compatible with Spoon](https://github.com/square/spoon#screenshots) and pulls them after each test.

For now you can use [`spoon-client` library from Spoon](https://github.com/square/spoon#screenshots).

Eventually we will suggest own library for making screenshots that'll be more configurable than spoon-client and will be able to use UIAutomator for that to capture whole device screen.

**Comment by RodrigoAmaroEng** [comment]
Hey @artem-zinnatullin, thanks for the answer.
I just managed to find what was the problem after playing a bit with your source code. Looks like the class [TestRun.kt](https://github.com/gojuno/composer/blob/master/composer/src/main/kotlin/com/gojuno/composer/TestRun.kt) line 169 builds a path with the test class full name (com.package.TestClass) while my version of Spoon (really don't know why) saves it with the simple name (TestClass). I've made a fix that's working here and i can send if you want it. Really like the tool and i'm willing to help with some ideas and fixes

**Comment by trevjonez** [comment]
Falcon spoon compat is my current favorite if I might suggest it here.

https://github.com/jraska/Falcon

**Comment by artem-zinnatullin** [comment]
Yep, although it doesn't screenshot windows that are shown by other processes (ie "Some app has stopped" dialogs and so on).

Juno uses combination of 3 ways to do a screenshot: UIAutomator which falls back to Falcon which falls back to Spoon haha, actually we never saw Falcon failure so UIAutomator with fall back to Falcon should be enough.
